### ISSUE TITLE
Routing not showing under menu F2

### ISSUE THREAD

**Issue by HappyBear-btc** [edouardparis/lntop#108]
![Screenshot_4](https://user-images.githubusercontent.com/122559990/236231084-6712fec9-fc26-43b7-87b6-10e60b10c44a.jpg)

I run a node on amd64, followed the raspibolt/miniblot guide.
after installing lntop the menu only showing channel and transactions without routing.

**Comment by HappyBear-btc** [comment]
I added the text to config file. still routing is not showing

**Comment by edouardparis** [comment]
Sorry I misread the guide, I think you have the version 0.1 that does not have the routing panel feature.
I compiled and signed a new x86_64 binary to the [v0.4.0 release](https://github.com/edouardparis/lntop/releases/tag/v0.4.0)

**Comment by HappyBear-btc** [comment]
thank you so much!
I downloaded it but couldn't install. I followed the guide on minibolt and did the following:
$ wget https://github.com/edouardparis/lntop/releases/download/v0.4.0/lntop-v0.4.0_Linux_x86_64.tar.gz
$ tar -xvf lntop-v0.4.0_Linux_x86_64.tar.gz
$ sudo install -m 0755 -o root -g root -t /usr/local/bin ./lntop

and I got this error:
$ install: cannot stat './lntop': No such file or directory

I also tried the instructions from github but this error:
Command 'lntop' not found, did you mean:
  command 'sntop' from deb sntop (1.4.3-6)
Try: sudo apt install <deb name>
![image](https://user-images.githubusercontent.com/122559990/236883934-a2ae5d84-85a4-4d02-832a-d8a3a2b86783.png)

**Comment by edouardparis** [comment]
` tar -xvf lntop-v0.4.0_Linux_x86_64.tar.gz` must have extract the files in `lntop-v0.4.0-Linux_x86_64`
so you may do: ` sudo install -m 0755 -o root -g root -t /usr/local/bin ./lntop-v0.4.0-Linux_x86_64/lntop` instead

`go install` will move the binary in your $GOBIN wich may not be in your bashrc 
I think you can add it with `export PATH="$PATH:$HOME/go/bin"`

`go build` will build the binary in the directory you are currently. so I think you can run it with 
`cd ~/lntop && ./lntop` because you already build it

**Comment by HappyBear-btc** [comment]
Hi thanks! actually I did slightly different before I read your comment
sudo install -m 0755 -o root -g root -t /usr/local/bin release-v0.4.0-Linux-x86_64/lntop

and it seems to work now.
![image](https://user-images.githubusercontent.com/122559990/236887201-06b19fc8-c4a4-4ec4-8a53-94511aca47e6.png)
